import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/app/component/header/Header";
import Footer from "@/app/component/footer/Footer";
import IGraduate from "@/icon/IGraduate";
import { Be_Vietnam_Pro } from "next/font/google";
const inter = Inter({subsets: ["latin"]});
const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700", "900"], // Load đủ các độ đậm cần thiết
  variable: "--font-be-vietnam", // Tạo biến CSS để dùng trong SCSS
  display: "swap",
});
export const metadata: Metadata = {
    title: "Sano Media Việt Nam",
    description: "Generated by create next app",
    icons: "./image/logo1.png",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={beVietnamPro.variable}>
        <Header/>
        <div className="main-children">
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
